### ISSUE TITLE
KC-API-KEY not exists

### ISSUE THREAD

**Issue by AlexField26** [Kucoin/kucoin-futures-python-sdk#12]
Hello community,

has anyone successfully used this lib for trading? I tried a minimal example, but i am always getting the error, that the API-KEY does not exist:

`from kucoin_futures.client import Trade

api_key = 'xxxxxxx'
api_secret = 'xxxxxxx'
api_passphrase = 'xxxxxxx'
url='https://api-futures.kucoin.com'

client = Trade(key=api_key, secret=api_secret, passphrase=api_passphrase, is_sandbox=False, url=url)
order_id = client.create_limit_order('XBTUSDM', 'buy', '1', '30', '8600')`

Can anyone assit?

Regards
Alex

**Comment by mehmetboraezer** [comment]
Hi Alex,

I got the same error today, maybe you created API key from spot settings like me. You should create new API key from https://futures.kucoin.com/api. 👍

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
