### ISSUE TITLE
500-{"code":"100000","msg":"Service not available temporarily, please try it later."}

### ISSUE THREAD

**Issue by aliniko79** [Kucoin/kucoin-futures-python-sdk#15]
`from kucoin_futures.client import Market

client=Market(key=key, secret=secret, passphrase=passphrase, is_sandbox=False, url=url)
k=client.get_ticker('BTCUSDT')
print(k)`

when I run this code it gives me this error:
Exception: 500-{"code":"100000","msg":"Service not available temporarily, please try it later."}

**Comment by vatttanweb** [comment]
Could you solve this problem?

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, please refer to our latest documentation: https://www.kucoin.com/docs/beginners/introduction
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
