### ISSUE TITLE
create_market_order negative response. 

### ISSUE THREAD

**Issue by zavataafnan** [Kucoin/kucoin-futures-python-sdk#20]
Hi All, 
Unfortunately, I always got this error, I can put limit order, But I can not create_market_order

order_id = client.create_market_order('XBTUSDM', 'buy', '1', size='60')

200-{"code":"300013","msg":"Unable to proceed the operation, theres no contra order in order book."}

Best Regards,
Mostafa

**Comment by facetoface10101980** [comment]
I've got the same problem.
Any ideas? Anyone?

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
