### ISSUE TITLE
How to define leverage and TP & SL?

### ISSUE THREAD

**Issue by wkh7777** [Kucoin/kucoin-futures-python-sdk#21]

**Comment by bermoodastar** [comment]
You can send the value for `leverage` in the body of the trade request. 
 ```
body = {
                'clientOid': market_order_cid,
                'side': 'sell',
                'symbol': symbol,
                'type': 'market',
                'leverage': self.leverage,
                'size': quantity
            }
```
P.S. 
I don't use this library for trading, I just create and send a normal HTTP Request using `requests.post`

**Comment by BaseMax** [comment]
> body = {
>                'clientOid': market_order_cid,
>                'side': 'sell',
>                'symbol': symbol,
>                'type': 'market',
>                'leverage': self.leverage,
>                'size': quantity
>  }


What about **price**? @bermoodastar

**Comment by ISAAC-XXYYZZ** [comment]
For more detailed information, please refer to our documentation:
https://www.kucoin.com/docs/rest/futures-trading/orders/place-order
