### ISSUE TITLE
Getting Data

### ISSUE THREAD

**Issue by misam72** [Kucoin/kucoin-futures-python-sdk#23]
Which topic should I use to get 1 min candles of BTC in Kucoin futures API?
How can I get the last price of BTC in kucoin futures API?
I've use '/market/candles:BTC-USDT_1min' for spot in python. What address is same as this for futures?

**Comment by progressivehed** [comment]
Hi

If you mean candles in future via websocket, it is not supported.

The topic you  mentioned belongs to Spot and we don't have it for future at the moment

**Comment by ISAAC-XXYYZZ** [comment]
We now support the following types: 1min, 3min, 5min, 15min, 30min, 1hour, 2hour, 4hour, 8hour, 12hour, 1day, 1week, 1month.
For more detailed information, please refer to our documentation: https://www.kucoin.com/docs/websocket/futures-trading/public-channels/klines
