### ISSUE TITLE
entire market orderbook

### ISSUE THREAD

**Issue by pypiHat** [Kucoin/kucoin-futures-python-sdk#25]
Hi
is there a way to reach the entire market orderbooks with the depth of 10?
what I mean by entire market is all coins/tokens exist on the Kucoin and order books of them?

Best,

**Comment by progressivehed** [comment]
Hello

Do you mean to pull these data at once from one endpoint?

**Comment by rootx-dev** [comment]
> Hello
> 
> Do you mean to pull these data at once from one endpoint?

yes getting all coins order book from one endpoint. is there any way or solutions?

**Comment by ISAAC-XXYYZZ** [comment]
Sorry, we currently do not have a similar interface. We recommend using the relevant trading pairs to obtain market data.
