### ISSUE TITLE
Order Creation Failing 

### ISSUE THREAD

**Issue by programerr01** [Kucoin/kucoin-futures-python-sdk#39]
i am getting this error when running this code 
`client.create_market_order("XBTUSDM","buy",'1','0.001')`
error
`requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-sandbox-futures.kucoin.com', port=443): Read timed out. (read timeout=5)
`

**Comment by progressivehed** [comment]
Hello there.

Issue is from Sandbox server. It will be solved if you retry in minutes later

**Comment by ISAAC-XXYYZZ** [comment]
We have temporarily suspended support for the Sandbox environment.
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
