### ISSUE TITLE
cannot import name 'KumexBaseRestApi'

### ISSUE THREAD

**Issue by garagesteve1155** [Kucoin/kucoin-futures-python-sdk#4]
Installed using pip, then ran this code:

from kucoin_futures.client import Market
client = Market(url='https://api-futures.kucoin.io')
klines = client.get_ticker("XBTUSDM")
print(klines)

Then encountered this error:

Traceback (most recent call last):
  File "futures.py", line 1, in <module>
    from kucoin_futures.client import Market
  File "/usr/local/lib/python3.6/dist-packages/kucoin_futures/client.py", line 4, in <module>
    from kucoin_futures.ws_token.token import GetToken
  File "/usr/local/lib/python3.6/dist-packages/kucoin_futures/ws_token/token.py", line 1, in <module>
    from kucoin_futures.base_request.base_request import KumexBaseRestApi
ImportError: cannot import name 'KumexBaseRestApi'

**Comment by garagesteve1155** [comment]
problem was in token.py

**Comment by edithkucoin** [comment]
hello,please try again. I find the issue is fixed.

**Comment by edithkucoin** [comment]
> problem was in token.py

issue is fixed.
