### ISSUE TITLE
Exception: 400-{"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}

### ISSUE THREAD

**Issue by AdrianOM98** [Kucoin/kucoin-futures-python-sdk#42]
![imagen](https://user-images.githubusercontent.com/112784813/188324861-8f15d222-bb30-4bbe-93c0-4b497272ab71.png)
 
i try make an orden or another operation whith module Trade.
help me please.

**Comment by Gettippi** [comment]
Hey there,

I had a similar issue which is solved easily:
For some reason, the computer I was running the program on was not on time. 

I've synced the Windows clock and the problem disappeared.

Hope it helps you as well

**Comment by yfprime** [comment]
> Hey there,
> 
> I had a similar issue which is solved easily: For some reason, the computer I was running the program on was not on time.
> 
> I've synced the Windows clock and the problem disappeared.
> 
> Hope it helps you as well

I have the same issue occasionally on an Ubuntu VM, even if I sync successfully every 15 seconds.

**Comment by guimauveb** [comment]
Even when using the server time from the `/api/v1/timestamp` endpoint I encounter this error on almost every level2 snapshot requests. 
The timestamp is well within the 5 seconds interval mentioned [here](https://www.kucoin.com/docs/basic-info/connection-method/types/timestamps) , so there must be something else.

**Comment by yfprime** [comment]
Has anyone found a fix for this?

**Comment by ISAAC-XXYYZZ** [comment]
I ran the code following your samples, and everything works perfectly.
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.

**Comment by Lordeleal** [comment]
![error kukoin ](https://github.com/user-attachments/assets/417a1ea8-a426-4266-ab5a-d68b09e33776)
same error, was anyone able to fix it?
