### ISSUE TITLE
{"code":"100001","msg":"The quantity parameter cannot be empty."}

### ISSUE THREAD

**Issue by hesamz3090** [Kucoin/kucoin-futures-python-sdk#47]
Hello this is my code I have balance and set size in def but market open didn't open and get me this error this is my code :

`api_key = '###'`
`api_secret= '###'`
`api_passphrase= '###'`

`client = Trade(key=api_key, secret=api_secret, passphrase=api_passphrase, is_sandbox=False, url='')`
`order_id = client.create_market_order('ETHUSDTM', 'buy', '0.01')`

**Comment by enigmatized** [comment]
I found if I downloaded the repo, then added a size parameter, I was able to make orders just fine.

`        params = {
            'symbol': symbol,
            'side': side,
            'leverage': lever,
            'type': 'market',
            'size': 1

        }`

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
