### ISSUE TITLE
sandbox URL does not exist

### ISSUE THREAD

**Issue by ferdinandhodl** [Kucoin/kucoin-futures-python-sdk#53]
; <<>> DiG 9.10.6 <<>> api-sandbox-futures.kucoin.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 51516
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api-sandbox-futures.kucoin.com.	IN	A

**Comment by ISAAC-XXYYZZ** [comment]
We have temporarily suspended support for the Sandbox environment.

For more detailed information, please refer to our documentation: https://www.kucoin.com/docs/beginners/sandbox
